### ISSUE TITLE
PostCSS line return parsing error

### ISSUE THREAD

**Issue by rajoouddin** [pax2pay/model-cde#33]
Dependabot ([#9](https://github.com/pax2pay/model-cde/security/dependabot/9)) has alerted with the following;

The latest possible version that can be installed is 8.3.5 because of the following conflicting dependencies:

eslint-plugin-prettierx@0.18.0 requires postcss@8.3.5 via prettierx@0.19.2
prettierx@0.18.0 requires postcss@8.3.5 via prettierx@0.19.2
No patched version available for postcss
The earliest fixed version is 8.4.31.

Package: postcss (npm)
Affected versions: < 8.4.31
Patched version: 8.4.31
An issue was discovered in PostCSS before 8.4.31. It affects linters using PostCSS to parse external Cascading Style Sheets (CSS). There may be \r discrepancies, as demonstrated by @font-face{ font:(\r/*);} in a rule.

This vulnerability affects linters using PostCSS to parse external untrusted CSS. An attacker can prepare CSS in such a way that it will contains parts parsed by PostCSS as a CSS comment. After processing by PostCSS, it will be included in the PostCSS output in CSS nodes (rules, properties) despite being originally included in a comment.

---

I came across these that may help;
- There look to be updates for eslint-plugin-prettierx - https://github.com/utily/eslint-plugin-prettierx/tree/utily-20231004
- I did come across this for prettierx - https://github.com/brodybits/prettierx/tree/renovate/npm-postcss-vulnerability

**Comment by fredrikbryntesson** [comment]
prettierx fix "prettierx": "github:utily/prettierx#utily-20231004"
eslint-plugin-prettierx fix "eslint-plugin-prettierx": "github:utily/eslint-plugin-prettierx#utily-20231004"
